name: tcm
channels:
  - defaults
dependencies:
  - bidict=0.21.2
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cffi=1.15.1
  - click=8.0.4
  - cryptography=41.0.2
  - dnspython=2.2.1
  - eventlet=0.33.1
  - flask=2.2.2
  - flask-socketio=5.3.1
  - flask_cors=3.0.10
  - greenlet=2.0.1
  - idna=3.4
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - libffi=3.4.4
  - libuuid=1.41.5
  - markupsafe=2.1.1
  - ncurses=6.4
  - openssl=3.0.10
  - pycparser=2.21
  - pyopenssl=23.2.0
  - python=3.11.4
  - python-engineio=4.1.0
  - python-socketio=5.3.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - werkzeug=2.2.3
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - pip==23.3.2
